"""add audit hash chain fields

Revision ID: 16bd1cbdbd34
Revises: 23c8c0e5c6dd
Create Date: 2026-09-18 23:27:00.766005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bd1cbdbd34'
down_revision: Union[str, Sequence[str], None] = '23c8c0e5c6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prev_hash', sa.String(length=64), nullable=True, comment='前一条日志的哈希'))
        batch_op.add_column(sa.Column('entry_hash', sa.String(length=64), nullable=True, comment='本条日志的链式哈希'))
        batch_op.create_index(batch_op.f('ix_operation_logs_entry_hash'), ['entry_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_logs_entry_hash'))
        batch_op.drop_column('entry_hash')
        batch_op.drop_column('prev_hash')

    # ### end Alembic commands ###
