"""add token_version for token revocation

Revision ID: 23c8c0e5c6dd
Revises: 8e843f2098de
Create Date: 2026-09-18 22:55:56.503991

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c8c0e5c6dd'
down_revision: str | Sequence[str] | None = '8e843f2098de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False, comment='token 版本；改密/重置/删除时自增，使已签发的旧 token 立即失效'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_version')

    # ### end Alembic commands ###
