"""add indexes for hot filter columns

Revision ID: 6b0297d0f9fa
Revises: ea3189f77aed
Create Date: 2026-09-18 21:28:57.208471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0297d0f9fa'
down_revision: Union[str, Sequence[str], None] = 'ea3189f77aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applications_assigned_reviewer_id'), 'applications', ['assigned_reviewer_id'], unique=False)
    op.create_index(op.f('ix_applications_customer_id'), 'applications', ['customer_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_customers_assigned_salesman_id'), 'customers', ['assigned_salesman_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_application_id'), 'feedbacks', ['application_id'], unique=False)
    op.create_index(op.f('ix_materials_application_id'), 'materials', ['application_id'], unique=False)
    op.create_index(op.f('ix_materials_audit_status'), 'materials', ['audit_status'], unique=False)
    op.create_index(op.f('ix_materials_category'), 'materials', ['category'], unique=False)
    op.create_index(op.f('ix_reviews_application_id'), 'reviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_reviews_material_id'), 'reviews', ['material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_material_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_application_id'), table_name='reviews')
    op.drop_index(op.f('ix_materials_category'), table_name='materials')
    op.drop_index(op.f('ix_materials_audit_status'), table_name='materials')
    op.drop_index(op.f('ix_materials_application_id'), table_name='materials')
    op.drop_index(op.f('ix_feedbacks_application_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_customers_assigned_salesman_id'), table_name='customers')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_customer_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_assigned_reviewer_id'), table_name='applications')
    # ### end Alembic commands ###
