"""add client error reports

Revision ID: 7745fb77bcce
Revises: 3c107d996841
Create Date: 2026-09-18 23:48:19.818652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7745fb77bcce'
down_revision: Union[str, Sequence[str], None] = '3c107d996841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False, comment='错误信息'),
    sa.Column('stack', sa.Text(), nullable=True, comment='堆栈（截断保存）'),
    sa.Column('url', sa.String(length=500), nullable=True, comment='出错页面路径'),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_errors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_errors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_errors_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_errors_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_errors_username'))
        batch_op.drop_index(batch_op.f('ix_client_errors_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_errors_id'))
        batch_op.drop_index(batch_op.f('ix_client_errors_created_at'))

    op.drop_table('client_errors')
    # ### end Alembic commands ###
