"""add login attempt/lock tables and material version unique constraint

Revision ID: 840eaf5a954c
Revises: 6b0297d0f9fa
Create Date: 2026-09-18 21:47:42.284302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840eaf5a954c'
down_revision: Union[str, Sequence[str], None] = '6b0297d0f9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_locks_id'), 'account_locks', ['id'], unique=False)
    op.create_index(op.f('ix_account_locks_username'), 'account_locks', ['username'], unique=True)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False, comment='ip 或 account'),
    sa.Column('key', sa.String(length=120), nullable=False, comment='IP 地址或用户名'),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False, comment='该次尝试是否成功'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_login_attempts_key'), 'login_attempts', ['key'], unique=False)
    op.create_index(op.f('ix_login_attempts_scope'), 'login_attempts', ['scope'], unique=False)
    # SQLite 不支持 ALTER 加约束，必须走 batch 模式（copy-and-move）；
    # PostgreSQL 下 batch_alter_table 等价于普通 ALTER，无副作用。
    with op.batch_alter_table('materials') as batch_op:
        batch_op.create_unique_constraint(
            'uq_material_app_category_version', ['application_id', 'category', 'version']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials') as batch_op:
        batch_op.drop_constraint('uq_material_app_category_version', type_='unique')
    op.drop_index(op.f('ix_login_attempts_scope'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_key'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_account_locks_username'), table_name='account_locks')
    op.drop_index(op.f('ix_account_locks_id'), table_name='account_locks')
    op.drop_table('account_locks')
    # ### end Alembic commands ###
