"""add must_change_password and password_changed_at

Revision ID: 8e843f2098de
Revises: 840eaf5a954c
Create Date: 2026-09-18 22:25:16.678328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e843f2098de'
down_revision: Union[str, Sequence[str], None] = '840eaf5a954c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, comment='是否强制修改密码（种子账号/管理员重置后置位，登录后需先改密）'))
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(), nullable=True, comment='最近一次修改密码时间'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_changed_at')
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
